#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
ynh_script_progression "Modify Configuration..."

if [ $change_path -eq 1 ]; then
    cp "$install_dir/live/packages/web/dist/app.js.orginal" "$install_dir/live/packages/web/dist/app.js"
    # If $new_path is used modify .js file for a working app on a subpath
    if [ $new_path != "/" ]; then
        ynh_replace --match="/components/" --replace="$new_path/components/" --file="$install_dir/live/packages/web/dist/app.js"
    fi
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
