#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

if [ -z "${snserver_domain:-}" ]; then
    snserver_domain="api.standardnotes.com"
    ynh_app_setting_set --key=snserver_domain --value="$snserver_domain"
fi

if ynh_app_upgrading_from_version_before 3.66.0~ynh1; then
    # Remove old service
    ynh_script_progression "Removing $app service..."
    yunohost service remove "$app"
    ynh_config_remove_systemd

    # Remove unneeded ruby
    ynh_ruby_remove
    ynh_safe_rm "$install_dir/.bundle"
    ynh_safe_rm "$install_dir/.ruby-version"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/live" --full_replace

#=================================================
# BUILDING
#=================================================
ynh_script_progression "Building... ( This may take a while... )" #131

pushd "$install_dir/live"

    ynh_hide_warnings ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=$node_max_old_space_size" node_load_PATH" yarn install --immutable
    ynh_hide_warnings ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=$node_max_old_space_size" node_load_PATH" yarn build:web
popd

chown -R "$app:www-data" "$install_dir"

#=================================================
# Modify Config
#=================================================
ynh_script_progression "Configuring..."

# If $path is used modify .js file for a working app on a subpath
cp "$install_dir/live/packages/web/dist/app.js" "$install_dir/live/packages/web/dist/app.js.orginal"
if [ "$path" != "/" ]; then
    ynh_replace --match="/components/" --replace="$path/components/" --file="$install_dir/live/packages/web/dist/app.js"
fi

# Modify Config
index_file="$install_dir/live/packages/web/dist/index.html"
ynh_replace --match="\(defaultSyncServer = \).*" --replace="\1\"https://$snserver_domain\"" --file="$index_file"
ynh_replace --match="\(defaultFilesHost = \).*" --replace="\1\"\"" --file="$index_file"
ynh_replace --match="\(enabledUnfinishedFeatures = \).*" --replace="\1false" --file="$index_file"
ynh_replace --match="\(websocketUrl = \).*" --replace="\1\"\"" --file="$index_file"
ynh_replace --match="\(purchaseUrl = \).*" --replace="\1\"\"" --file="$index_file"
ynh_replace --match="\(plansUrl = \).*" --replace="\1\"\"" --file="$index_file"
ynh_replace --match="\(dashboardUrl =\).*" --replace="\1\"\"" --file="$index_file"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
